apiVersion: v1
appVersion: "1.0"
description: Sonarr - Automatic downloader for TV Shows :)
name: sonarr
version: 0.1.0
icon: https://bpafoshizle.github.io/home-kube-media/helm/charts/sonarr/logo/sonarr.png