apiVersion: v1
appVersion: "1.0"
description: Prowlarr - an indexer manager that integrates seamlessly with Lidarr, Mylar3, Radarr, Readarr, and Sonarr
name: prowlarr
version: 0.1.0
icon: https://bpafoshizle.github.io/home-kube-media/helm/charts/prowlarr/logo/prowlarr.png