
replicaCount: 1

image:
  repository: ghcr.io/bpafoshizle/home-kube-media/prowlarr
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-docker-home-kube-media

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

volumes:
  - name: media-lynott
    persistentVolumeClaim:
      claimName: media-lynott

volumeMounts:
  - name: media-lynott
    mountPath: "/config"
    subPath: "configs/prowlarr"

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 256Mi
    cpu: 0.5

nodeSelector: {}

tolerations: []

affinity: {}