name: Main and Tags

on:
  push:
    # Publish main branch as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  
  workflow_dispatch:

jobs:
  show-key-values:
    name: show values of variables
    runs-on: ubuntu-latest

    steps:
      - name: run test command
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}

  call-build-and-push-readarr:
    uses: bpafoshizle/actions/.github/workflows/docker-build-push-ghcr.yml@main
    with:
      dockerfile: docker/readarr/Dockerfile
      platform: 'linux/amd64,linux/arm64'
    secrets:
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

  call-build-and-push-radar:
    uses: bpafoshizle/actions/.github/workflows/docker-build-push-ghcr.yml@main
    with:
      dockerfile: docker/radarr/Dockerfile
      platform: 'linux/amd64,linux/arm64'
      build_dir: docker/radarr
    secrets:
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}